FROM node:20.0.0-alpine as build

ENV PORT 8080
ARG NEXT_PUBLIC_SANITY_PROJECT_ID
ARG NEXT_PUBLIC_SANITY_DATASET
ARG NEXT_PUBLIC_SANITY_API_VERSION
ARG SANITY_API_READ_TOKEN
# Create app directory
RUN mkdir -p /usr/src/app/
ENV ENV NEXT_PUBLIC_SANITY_PROJECT_ID ${NEXT_PUBLIC_SANITY_PROJECT_ID}
ENV NEXT_PUBLIC_SANITY_DATASET ${NEXT_PUBLIC_SANITY_DATASET}
ENV NEXT_PUBLIC_SANITY_API_VERSION ${NEXT_PUBLIC_SANITY_API_VERSION}
ENV SANITY_API_READ_TOKEN ${SANITY_API_READ_TOKEN}

RUN echo "NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}"
RUN echo "NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}"
RUN echo "NEXT_PUBLIC_SANITY_API_VERSION=${NEXT_PUBLIC_SANITY_API_VERSION}"
RUN echo "SANITY_API_READ_TOKEN=${SANITY_API_READ_TOKEN}"




WORKDIR /usr/src/app/

# Installing dependencies
COPY package*.json /usr/src/app/
RUN npm install

# Copying source files
COPY . /usr/src/app/

# Building app
RUN npx next telemetry disable
RUN npm run build
EXPOSE 8080

# Running the app
CMD "npm" "run" "dev"
